version: "3"

services:
  lychee:
    container_name: Lychee
    image: siku2/lychee
    build: .
    depends_on:
      - mysql
    restart: always
    ports:
      - 80:80
    volumes:
      - pictures:/pictures
      - config:/config
    networks:
      - backend
  mysql:
    container_name: MySQL
    image: mysql:5
    restart: always
    expose:
      - 3306
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=lychee
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

volumes:
  pictures: {}
  config: {}
  db: {}

networks:
  backend: {}